language: cpp

env:
    global:
        - MAKE_CMD="make -j"

matrix:
    include:
        - os: linux
          compiler: gcc-5
        - os: linux
          compiler: clang-3.6

install:
    - git clone https://github.com/lxde/qtermwidget
    - cd qtermwidget && mkdir build && cd build && cmake ../ && make -j && sudo make install

script:
    - cd zdict.qt && make -j

addons:
    apt:
        sources:
            - llvm-toolchain-precise-3.6
            - ubuntu-toolchain-r-test
        packages:
            - g++-5-multilib
            - clang-3.6
            - cmake
